/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#15157d",
        "primary-container": "#2e3192",
        "on-primary": "#ffffff",
        "on-primary-container": "#9da1ff",
        "inverse-primary": "#c0c1ff",
        secondary: "#515f74",
        "secondary-container": "#d5e3fc",
        "on-secondary-container": "#57657a",
        surface: "#fcf8ff",
        "surface-dim": "#dbd9e1",
        "surface-bright": "#fcf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f2fb",
        "surface-container": "#f0ecf5",
        "surface-container-high": "#eae7f0",
        "surface-container-highest": "#e4e1ea",
        "on-surface": "#1b1b21",
        "on-surface-variant": "#464652",
        "inverse-surface": "#303036",
        outline: "#777683",
        "outline-variant": "#c7c5d4",
        "surface-tint": "#4f54b4",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        background: "#fcf8ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "48px",
        gutter: "24px",
        margin: "32px",
        max_width: "1440px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Manrope", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-base": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

